RANDOM_STATE = 42

DEFAULT_THRESHOLD = 0.5
DEFAULT_EVALUATION_SCOPE = "full_offline_eval"
AUTO_RETRAIN_EVALUATION_SCOPE = "auto_retrain_holdout"

RETRAIN_THRESHOLD = 5

FULL_TRAIN_FEEDBACK_WEIGHT = 3
AUTO_RETRAIN_FEEDBACK_WEIGHT = 5

LINEAR_SVM_MAX_ITER = 10000
